# Lab: Data Preparation for Analysis — HR Employee Dataset
/ by altinai

In [ ]:
import pandas as pd
import numpy as np

employees = pd.DataFrame({
    "EmployeeID": [101, 102, 103, 103, 105, 106, 107, 108,
                   109, 110, 111, 112, 113, 114, 115],
    "FirstName": [
        "Ainura", "Bakyt", "Gulnara", "Gulnara", "Nurlan",
        "Aigul", "Beksultan", "Aisuluu", "Ermek", "Nurgul", "Daniyar", "Aizhan", "Kubat", "Perizat", "Adilet"
    ],
    "LastName": [
        "Asanova", "Kyzylov", "Mamatova", "Mamatova", "Abdyldaev",
        "Sultanova", "Toktogulov", "baisalova", "Kadyrov",
        "Jumabaeva ", "Turgunov", "Ryskulova", "Kadyraliev",
        "BAktybekova", "MOLDOKULOV"
    ],
    "Department": [
        "IT", "HR", "it", "IT", "Finance", "HR",
        " IT ", "Finance", "IT", "HR", "it",
        "Financing", "Information Tecnology", "HR", "finance"
    ],
    "Gender": [
        "F", "m", "F", "f", "M", "F", "M", "F",
        "M", "F", "M", "F", "M", "F", "m"
    ],
    "Age": [
        "28", "35", "29", "29", "150", "31", "33",
        "27", "30", "38", "26", "34", "29", "32", "31"
    ],
    "Salary": [
        "80000", "65000", np.nan, np.nan, "90000", "70000",
        "unknown", "62000", "85000", "58000", "72000",
        "66000", "78000", "88000", "61000"
    ],
    "HireDate": [
        "2023-01-15", "2022-06-10", "2024-03-01", "2024-03-01",
        "2021-11-20", "2023-08-05", "2020-05-12", "2022-09-18",
        "2021-03-25", "2019-07-14", "2023-04-18", "2020-10-02",
        "2022-12-11", "2021-08-30", "2023-06-22"
    ],
    "PerformanceScore": [
        4.2, 3.8, 4.5, 4.5, 4.0, 3.9, 4.1,
        3.7, 4.3, 3.6, 4.4, 3.8, 4.2, "4.0", 3.9
    ]
})

departments = pd.DataFrame({
    "DepartmentID": [1, 2, 3],
    "DepartmentName": ["IT", "HR", "Finance"],
    "Location": ["Bishkek", "Osh", "Bishkek"]
})

In [6]:
# copy and do not change original
df = employees.copy()
df

,EmployeeID,FirstName,LastName,Department,Gender,Age,Salary,HireDate,PerformanceScore
0,101,Ainura,Asanova,IT,F,28,80000,2023-01-15,4.2
1,102,Bakyt,Kyzylov,HR,m,35,65000,2022-06-10,3.8
2,103,Gulnara,Mamatova,it,F,29,NaN,2024-03-01,4.5
3,103,Gulnara,Mamatova,IT,f,29,NaN,2024-03-01,4.5
4,105,Nurlan,Abdyldaev,Finance,M,150,90000,2021-11-20,4.0
5,106,Aigul,Sultanova,HR,F,31,70000,2023-08-05,3.9
6,107,Beksultan,Toktogulov,IT,M,33,unknown,2020-05-12,4.1
7,108,Aisuluu,baisalova,Finance,F,27,62000,2022-09-18,3.7
8,109,Ermek,Kadyrov,IT,M,30,85000,2021-03-25,4.3
9,110,Nurgul,Jumabaeva,HR,F,38,58000,2019-07-14,3.6
10,111,Daniyar,Turgunov,it,M,26,72000,2023-04-18,4.4
11,112,Aizhan,Ryskulova,Financing,F,34,66000,2020-10-02,3.8
12,113,Kubat,Kadyraliev,Information Tecnology,M,29,78000,2022-12-11,4.2
13,114,Perizat,BAktybekova,HR,F,32,88000,2021-08-30,4.0
14,115,Adilet,MOLDOKULOV,finance,m,31,61000,2023-06-22,3.9

## Task 1 — Inspect the Dataset
Check the number of 
1.rows and columns, 


2.data types of all columns, 


3.and data types of selected columns such as Salary, Age, and HireDate. 


4. Use notna() to identify rows where Salary is present.


5. Identify all data-quality problems: missing values, duplicates, inconsistent department names, incorrect age, and dates stored as text. 


6. .Remove extra spaces if any. 

7.  Check whether all values in PerformanceScore are numeric.

In [34]:
print("\n1) 15 is rows amount, 9 is columns:")
print("Rows, columns:", df.shape) 
print("\n2)data types of all columns")
print(df.dtypes)

print("\n3) print data types Salary, Age, and HireDate.")
print(df[["Salary", "Age", "HireDate"]].dtypes)

1) 15 is rows amount, 9 is columns:
Rows, columns: (15, 9)

2)data types of all columns
EmployeeID           int64
FirstName              str
LastName               str
Department             str
Gender                 str
Age                    str
Salary                 str
HireDate               str
PerformanceScore    object
dtype: object

3) print data types Salary, Age, and HireDate.
Salary      str
Age         str
HireDate    str
dtype: object

In [35]:
print("\n4) rows where Salary is present")
df[df["Salary"].notna()]

4) rows where Salary is present

,EmployeeID,FirstName,LastName,Department,Gender,Age,Salary,HireDate,PerformanceScore
0,101,Ainura,Asanova,IT,F,28,80000,2023-01-15,4.2
1,102,Bakyt,Kyzylov,HR,m,35,65000,2022-06-10,3.8
4,105,Nurlan,Abdyldaev,Finance,M,150,90000,2021-11-20,4.0
5,106,Aigul,Sultanova,HR,F,31,70000,2023-08-05,3.9
6,107,Beksultan,Toktogulov,IT,M,33,unknown,2020-05-12,4.1
7,108,Aisuluu,baisalova,Finance,F,27,62000,2022-09-18,3.7
8,109,Ermek,Kadyrov,IT,M,30,85000,2021-03-25,4.3
9,110,Nurgul,Jumabaeva,HR,F,38,58000,2019-07-14,3.6
10,111,Daniyar,Turgunov,it,M,26,72000,2023-04-18,4.4
11,112,Aizhan,Ryskulova,Financing,F,34,66000,2020-10-02,3.8
12,113,Kubat,Kadyraliev,Information Tecnology,M,29,78000,2022-12-11,4.2
13,114,Perizat,BAktybekova,HR,F,32,88000,2021-08-30,4.0
14,115,Adilet,MOLDOKULOV,finance,m,31,61000,2023-06-22,3.9

In [39]:
print("5) all data quantity problems\n")
print("Missing values per column:")
print(df.isna().sum())
print()
print("Fully duplicated rows:", df.duplicated().sum())
print("Duplicated EmployeeID:", df["EmployeeID"].duplicated().sum())
print("actually we have a dublicating row, but since values are row, 'it' and 'IT' confuse pandas and so it thinks they are not the same.\n that's why we need to trim and clean data first")
print(df.loc[[2,3]])

print()

print("Department values (raw):", sorted(df["Department"].unique().tolist()))
print("Age values (raw):", df["Age"].tolist())
print("Non-numeric Salary:", df.loc[pd.to_numeric(df["Salary"], errors="coerce").isna() & df["Salary"].notna(), "Salary"].tolist())

5) all data quantity problems

Missing values per column:
EmployeeID          0
FirstName           0
LastName            0
Department          0
Gender              0
Age                 0
Salary              2
HireDate            0
PerformanceScore    0
dtype: int64

Fully duplicated rows: 0
Duplicated EmployeeID: 1
actually we have a dublicating row, but since values are row, 'it' and 'IT' confuse pandas and so it thinks they are not the same.
 that's why we need to trim and clean data first
   EmployeeID FirstName  LastName Department Gender Age Salary    HireDate  \
2         103   Gulnara  Mamatova         it      F  29    NaN  2024-03-01
3         103   Gulnara  Mamatova         IT      f  29    NaN  2024-03-01

  PerformanceScore
2              4.5
3              4.5

Department values (raw): ['Finance', 'Financing', 'HR', 'IT', 'Information Tecnology', 'finance', 'it']
Age values (raw): ['28', '35', '29', '29', '150', '31', '33', '27', '30', '38', '26', '34', '29', '32', '31']
Non-numeric Salary: ['unknown']

In [37]:
print('remove extra spaces in every column with text')
for col in ["FirstName", "LastName", "Department", "Gender"]:
    df[col] = df[col].str.strip()

remove extra spaces in every column with text

In [38]:
# PerformanceScore is mixed (floats and string)
print(df["PerformanceScore"].dtype)

print('If it says int64 or float64, the values are all numeric. \nIf it says object, there is some text in the column.')

object
If it says int64 or float64, the values are all numeric.
If it says object, there is some text in the column.

### explanation
 5 rows × 9 columns


 Missing / bad salaries: 2 real `NaN` (employee 103 is dublicated and has Nan salary)

 
  1 text `"unknown"` (employee 107). 


  `notna()` shows only the rows where a salary is present but it does not undrstand that text`"unknown"` is a bad salary. so we have to find it another way


 Duplicates: employee 103 (Gulnara Mamatova) appears twice; the two rows differ only in spelling (`it`, `IT`, `F`, `f`), so they are counted as duplicates onlyafter standardising.
the same departments ahve different case: `IT`, `it`, `" IT "`, `Financing`, `Information Tecnology`, `finance` ...
Incorrect age: employee 105 has `150`.
Dates as text: `HireDate` is `object`.
Extra spaces: `"Jumabaeva "` and `" IT "` — removed with `str.strip()`.
PerformanceScore is mixed: floats plus one string `"4.0"` (employee 114), so the column is not purely numeric.
Case is also inconsistent in `LastName` (`baisalova`, `BAktybekova`, `MOLDOKULOV`) and `Gender` (`m`, `f`).


## Task 2 — Handle Missing Salaries
-Find missing values, 

-count them by column, and 

-calculate the percentage of missing values.

-Replace "unknown" in Salary with a missing value, convert Salary to a numeric type using errors="coerce", and replace empty Salary values with the median salary.


-Experiment with dropna() using axis, how, subset, and thresh. Explain what changes with each parameter.

In [40]:
# count and percentage of missing values by column (the "unknown" text is not yet counted)
missing = pd.DataFrame({"missing": df.isna().sum(), "percent": (df.isna().mean() * 100).round(2)})
missing

                  missing  percent
EmployeeID              0     0.00
FirstName               0     0.00
LastName                0     0.00
Department              0     0.00
Gender                  0     0.00
Age                     0     0.00
Salary                  2    13.33
HireDate                0     0.00
PerformanceScore        0     0.00

In [42]:
# "unknown" -> NaN, then convert to numeric
df["Salary"] = df["Salary"].replace("unknown", np.nan)
df["Salary"] = pd.to_numeric(df["Salary"], errors="coerce")
print(df["Salary"].dtype)

missing = pd.DataFrame({"missing": df.isna().sum(), "percent": (df.isna().mean() * 100).round(2)})
missing

float64

                  missing  percent
EmployeeID              0      0.0
FirstName               0      0.0
LastName                0      0.0
Department              0      0.0
Gender                  0      0.0
Age                     0      0.0
Salary                  3     20.0
HireDate                0      0.0
PerformanceScore        0      0.0

In [43]:
# fill the empty salaries with the median
median_salary = df["Salary"].median()
print("Median salary:", median_salary)
df["Salary"] = df["Salary"].fillna(median_salary)
df["Salary"].isna().sum()

Median salary: 71000.0

np.int64(0)

### Experiment with `dropna()`
Done on a fresh copy of the data **before** the salaries were filled, so the effect is visible.

In [44]:
test = employees.copy()
test["Salary"] = pd.to_numeric(test["Salary"], errors="coerce")
test.loc[0, "Age"] = np.nan      # one more NaN, in a different column, to show subset/thresh
print("original rows:", len(test))

print("default (axis=0, how='any'):      ", len(test.dropna()))
print("how='all':                        ", len(test.dropna(how="all")))
print("subset=['Salary']:                ", len(test.dropna(subset=["Salary"])))
print("subset=['Salary','Age']:          ", len(test.dropna(subset=["Salary", "Age"])))
print("thresh=9 (keep rows with >=9 non-NaN):", len(test.dropna(thresh=9)))
print("thresh=8:                         ", len(test.dropna(thresh=8)))
print("axis=1 (drop columns with any NaN):", list(test.dropna(axis=1).columns))

original rows: 15
default (axis=0, how='any'):       11
how='all':                         15
subset=['Salary']:                 12
subset=['Salary','Age']:           11
thresh=9 (keep rows with >=9 non-NaN): 11
thresh=8:                          15
axis=1 (drop columns with any NaN): ['EmployeeID', 'FirstName', 'LastName', 'Department', 'Gender', 'HireDate', 'PerformanceScore']

### Task 2 — explanation
* `"unknown"` is a *string*, so pandas does not see it as missing. `replace("unknown", np.nan)` makes it a real missing value, and `pd.to_numeric(..., errors="coerce")` converts the column to `float64` (anything unparsable would also become `NaN`).
* After this, `Salary` has 3 missing values (3 / 15 = **20 %**). They were filled with the **median** (not the mean) because the median is robust to outliers and keeps the distribution realistic.
* What each `dropna()` parameter changes:
  * `axis=0` (default) drops **rows**; `axis=1` drops **columns** that contain NaN.
  * `how="any"` (default) drops a row if *any* value is missing; `how="all"` only if *all* values are missing (nothing is dropped here).
  * `subset=[...]` only looks at the listed columns — dropping rows with missing `Salary` removes 3 rows, adding `Age` removes one more.
  * `thresh=n` keeps a row only if it has at least *n* non-missing values, which is a softer rule than `how="any"`.
* Dropping data is costly with only 15 rows, which is why imputation was chosen for `Salary`.

## Task 3 — Standardize Department Names

In [ ]:
print("Before:", sorted(df["Department"].unique().tolist()))

df["Department"] = (
    df["Department"]
    .str.strip()
    .str.replace("Information Tecnology", "IT", regex=False)
    .str.replace(r"^Financ\w*$", "Finance", regex=True, case=False)   # Financing / finance / Finance
    .str.upper()
    .replace({"FINANCE": "Finance"})
)

print("After: ", sorted(df["Department"].unique().tolist()))
df["Department"].value_counts()

In [ ]:
# the same kind of tidy-up for the other text columns
df["LastName"] = df["LastName"].str.strip().str.title()
df["Gender"] = df["Gender"].str.strip().str.upper()
print(df["Gender"].unique(), df["LastName"].tolist())

In [ ]:
# incorrect age
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
print(df.loc[(df["Age"] < 18) | (df["Age"] > 70), ["EmployeeID", "FirstName", "LastName", "Age"]])

In [ ]:
# decision: an age of 150 is impossible -> treat it as missing and fill it with the median age
df.loc[(df["Age"] < 18) | (df["Age"] > 70), "Age"] = np.nan
median_age = int(df["Age"].median())   # 30.5 -> 30, so Age can become an integer column
df["Age"] = df["Age"].fillna(median_age)
print("median age used:", median_age)
df["Age"].describe()

### Task 3 — explanation
* `str.strip()` removes the surrounding spaces (`" IT "`), `str.replace()` fixes the misspellings (`Information Tecnology` → `IT`, `Financing`/`finance` → `Finance`) and `str.upper()` makes the case consistent (`it` → `IT`). The unique values are now only **IT, HR, Finance**, matching `departments["DepartmentName"]`.
* `Age` 150 (employee 105, Nurlan Abdyldaev) is a data-entry error — nobody is 150 and we cannot know the real value. Deleting the whole employee would lose a valid salary and hire date, so the age was set to `NaN` and replaced with the **median age** (30.5, rounded down to 30 so the column can stay an integer). Other reasonable choices: leave it `NaN` (kept as nullable `Int64`) or ask HR for the real value.

## Task 4 — Remove Duplicates

In [ ]:
print("rows before:", len(df))
print("exact duplicates:", df.duplicated().sum())
df[df["EmployeeID"].duplicated(keep=False)]

In [ ]:
# step 1: exact duplicates (visible only after the cleaning above)
df = df.drop_duplicates()
print("after exact duplicates:", len(df))

# step 2: duplicates by EmployeeID
df = df.drop_duplicates(subset="EmployeeID")
print("after EmployeeID duplicates:", len(df))
df["EmployeeID"].is_unique

### Experiment with `drop_duplicates()`

In [ ]:
d = employees.copy()          # raw data, to see what happens to employee 103
print("original:                       ", len(d))
print("subset=EmployeeID, keep='first':", len(d.drop_duplicates(subset="EmployeeID", keep="first")),
      "-> keeps index", d.drop_duplicates(subset="EmployeeID", keep="first").query("EmployeeID == 103").index.tolist())
print("subset=EmployeeID, keep='last': ", len(d.drop_duplicates(subset="EmployeeID", keep="last")),
      "-> keeps index", d.drop_duplicates(subset="EmployeeID", keep="last").query("EmployeeID == 103").index.tolist())
print("subset=EmployeeID, keep=False:  ", len(d.drop_duplicates(subset="EmployeeID", keep=False)),
      "-> both 103 rows removed")
print("no subset (raw, exact match):   ", len(d.drop_duplicates()), "-> raw rows differ in case, so nothing is dropped")
print("subset=['FirstName','LastName']:", len(d.drop_duplicates(subset=["FirstName", "LastName"])))

### Task 4 — explanation
* After standardising `Department` and `Gender`, the two Gulnara Mamatova rows became identical, so `drop_duplicates()` removed one (**15 → 14 rows**). The second pass by `EmployeeID` removed nothing more — every ID is now unique.
* On the **raw** data `drop_duplicates()` finds nothing, because `it`/`IT` and `F`/`f` make the rows different — this is why cleaning must come before de-duplication.
* `subset` chooses which columns define a duplicate. `keep="first"` (default) keeps the first occurrence, `keep="last"` keeps the last, and `keep=False` removes **all** copies (including the original), which would wrongly delete employee 103 entirely — useful only for *finding* every row involved in a duplicate.

## Task 5 — Convert Data Types

In [ ]:
print(df.dtypes)

In [ ]:
df["Age"] = df["Age"].astype("Int64")
print("Age:", df["Age"].dtype)

df["Department"] = df["Department"].astype("category")
print("Department:", df["Department"].dtype, "| categories:", list(df["Department"].cat.categories))

df["Gender"] = df["Gender"].astype("category")
print("Gender:", df["Gender"].dtype, "| categories:", list(df["Gender"].cat.categories))

In [ ]:
# PerformanceScore contains the string "4.0" -> convert to numeric
df["PerformanceScore"] = pd.to_numeric(df["PerformanceScore"], errors="coerce")
print("PerformanceScore:", df["PerformanceScore"].dtype, "| missing:", df["PerformanceScore"].isna().sum())
print()
print(df.dtypes)

In [ ]:
# object vs category: memory usage
dept_obj = df["Department"].astype("object")
print("object  :", dept_obj.memory_usage(deep=True), "bytes")
print("category:", df["Department"].memory_usage(deep=True), "bytes")

### Task 5 — explanation
* `Int64` (capital I) is a **nullable integer**: unlike NumPy `int64` it can store `<NA>`, so a column of ages can stay integer even if a value is missing.
* **object vs category:** `object` stores every value as a separate Python string. `category` stores each unique label once and keeps small integer codes per row, which uses less memory, is faster for `groupby`/comparisons, and documents that the column has a fixed set of values (`IT`, `HR`, `Finance`). Use `object` for free text (names), `category` for low-cardinality labels.
* `PerformanceScore` held the text `"4.0"` (employee 114), so it was converted with `pd.to_numeric` to `float64`; no value was lost.

## Task 6 — Parse Hire Dates

In [ ]:
df["HireDate"] = pd.to_datetime(df["HireDate"], format="%Y-%m-%d", errors="coerce")
print(df["HireDate"].dtype)
print("unparsed dates:", df["HireDate"].isna().sum())

In [ ]:
df["HireYear"] = df["HireDate"].dt.year
df["HireMonth"] = df["HireDate"].dt.month
df["HireWeekday"] = df["HireDate"].dt.day_name()

# years worked up to a fixed reference date, so the result is reproducible
reference_date = pd.Timestamp("2025-01-01")
df["YearsWorked"] = ((reference_date - df["HireDate"]).dt.days / 365.25).round(1)

df[["EmployeeID", "HireDate", "HireYear", "HireMonth", "HireWeekday", "YearsWorked"]]

### Task 6 — explanation
* `pd.to_datetime` turns the text into `datetime64[ns]`, which allows date arithmetic and the `.dt` accessor. `errors="coerce"` would turn any unparsable date into `NaT` instead of raising an error (none were found).
* `.dt.year`, `.dt.month` and `.dt.day_name()` extract the parts used for time-based analysis (e.g. hires per year).
* **Years worked** = (reference date − hire date) in days ÷ 365.25. A fixed reference date (`2025-01-01`) is used so the notebook gives the same result every time; use `pd.Timestamp.today()` instead for "up to today".

## Task 7 — Rename Columns and Merge Datasets

In [ ]:
df = df.rename(columns={"Salary": "MonthlySalary", "HireDate": "EmploymentStartDate"})
print(df.columns.tolist())

In [ ]:
# Department is a category column; cast to object so it can be matched with a plain-text key
df["Department"] = df["Department"].astype("object")

merged = df.merge(
    departments,
    how="left",
    left_on="Department",
    right_on="DepartmentName",
)
print("rows before merge:", len(df), "| after merge:", len(merged))
print("missing values created by the merge:")
print(merged[["DepartmentID", "DepartmentName", "Location"]].isna().sum())
merged[["EmployeeID", "FirstName", "Department", "DepartmentID", "Location"]]

### Task 7 — explanation
* `rename(columns={...})` takes an `old: new` mapping; names not listed are left unchanged.
* The merge key is `Department` (employees) = `DepartmentName` (departments), so `left_on`/`right_on` are used. `how="left"` keeps **all** employees, adding `DepartmentID` and `Location`.
* Because the department names were standardised in Task 3, **no missing values** appeared and the row count stayed the same (no new duplicates either). Without the cleaning, `" IT "`, `it`, `Financing` and `Information Tecnology` would not have matched and would have produced `NaN` in `DepartmentID` and `Location`.

## Task 8 — Final Check and Summary

In [ ]:
final = merged.copy()
final["Department"] = final["Department"].astype("category")

print("Shape:", final.shape)
print()
final.info()

In [ ]:
print("Missing values:")
print(final.isna().sum()[final.isna().sum() > 0] if final.isna().any().any() else "none")
print()
print("Full duplicates:", final.duplicated().sum(), "| duplicate EmployeeID:", final["EmployeeID"].duplicated().sum())
print("Date column dtype:", final["EmploymentStartDate"].dtype)
print("Departments:", sorted(final["Department"].unique().tolist()))

In [ ]:
# raw data was never modified
print("raw employees still has", len(employees), "rows and dtypes:", employees["Age"].dtype, employees["Salary"].dtype)
final.head()

### Summary

**Problems found**
1. Almost every column stored as `object`: `Age`, `Salary`, `HireDate` as text, `PerformanceScore` mixed with a string.
2. Missing salaries: two `NaN` and one text value `"unknown"` (20 % of the column in total).
3. Inconsistent departments: different case, extra spaces and typos (`Financing`, `Information Tecnology`).
4. Impossible age (150) for employee 105.
5. A duplicate employee (ID 103) that was hidden by inconsistent case.
6. Extra spaces and inconsistent capitalisation in names and gender.

**Methods and parameters used**
* Inspection: `shape`, `info()`, `dtypes`, `isna().sum()`, `notna()`, `duplicated()`.
* Missing values: `replace("unknown", np.nan)`, `pd.to_numeric(errors="coerce")`, `fillna(median)`, plus `dropna(axis, how, subset, thresh)` experiments.
* Text cleaning: `str.strip()`, `str.replace()`, `str.upper()`, `str.title()`.
* Duplicates: `drop_duplicates()` with `subset`, `keep="first" / "last" / False`.
* Types: `astype("Int64")`, `astype("category")`, `pd.to_numeric`, `pd.to_datetime`, `.dt.year/.month/.day_name()`.
* Combining: `rename(columns=...)`, `merge(how="left", left_on, right_on)`.

**Result:** 14 unique employees, no missing values, no duplicates, correct data types, consistent department names, and a clean join with the department table (location added for everyone).

**Why data preparation matters before HR analysis:** averages and counts computed on dirty data are wrong — a duplicate inflates headcount, `"unknown"` or `NaN` breaks salary statistics, an age of 150 distorts the mean age, and inconsistent department names split one department into several groups or break joins. Clean, correctly-typed data makes every later result (salary by department, tenure, performance) trustworthy.